In [1]:
import numpy as np

In [15]:
x=np.array([10, 20, 30], dtype='int16')
print(x)

[10 20 30]


In [4]:
y=np.array([[15,20,6,8],[50,20,10,4]])
print(y)

[[15 20  6  8]
 [50 20 10  4]]


In [8]:
#get the dimesnion of numpy array
y.ndim


2

In [10]:
#get the dimesnion of numpy array
x.ndim

1

In [20]:
#get the shape of numpy array
y.shape

(2, 4)

In [16]:
#get the data type of numpy array
x.dtype

dtype('int16')

In [18]:
#get the size of numpy array
y.itemsize


4

In [19]:
#get the total size or total number of elements of numpy array
y.size

8

In [ ]:
# Accessing and changing elements, columns, rows etc


In [22]:
a=np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
#get a specific element
a[1,-2]


13

In [25]:
#get a specific element
a[1,5]

13

In [28]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
#get a specific column
a[:,5]

array([ 6, 13])

In [36]:
#get kinda fancy
a[0, 1:-1:2]

array([2, 4, 6])

In [37]:
#replace element
a[0,5]=10
a

array([[ 1,  2,  3,  4,  5, 10,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

3D EXAMPLE

In [42]:
b=np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [45]:
#get a specific element
b[0,1,1]

4

In [50]:
#replace specific elemment
b[:,1,:]=[[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

INITIALIAISING DIFFERENT TYPES OF ARRAYS

In [56]:
#all zero matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
#all ones matrix
np.ones((6,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [58]:
#any numbers matrix
np.full((3,3), 25)

array([[25, 25, 25],
       [25, 25, 25],
       [25, 25, 25]])

In [63]:
#any numbers matrix(full_like)
np.full_like(a, 5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [64]:
#any numbers matrix(full with shape)
np.full(a.shape, 5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [65]:
#get random decimal numbers
np.random.rand(4,2)

array([[0.0706728 , 0.49449409],
       [0.0809577 , 0.83539809],
       [0.42553125, 0.45347643],
       [0.08951941, 0.10737858]])

In [66]:
#get random decimal numbers using random sample
np.random.random_sample(a.shape)

array([[0.0651591 , 0.09412291, 0.99078042, 0.03467586, 0.48106064,
        0.48591069, 0.76415414],
       [0.19316577, 0.62786057, 0.71224562, 0.28598164, 0.61412521,
        0.41065457, 0.0488881 ]])

In [72]:
#get random integer numbers
np.random.randint(7, size=(4,4))


array([[6, 3, 5, 4],
       [3, 2, 6, 0],
       [5, 4, 6, 6],
       [3, 0, 4, 5]])

In [75]:
#get identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [83]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [86]:
x=np.array([1,2,3])
y=x.copy()
y[2]=200
x

array([1, 2, 3])

Mathematics

In [88]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [89]:
x+2

array([3, 4, 5, 6])

In [90]:
x/2

array([0.5, 1. , 1.5, 2. ])

In [91]:
x*2

array([2, 4, 6, 8])

In [92]:
x-2

array([-1,  0,  1,  2])

In [94]:
y=np.array([2,1,8,1])
x+y

array([ 3,  3, 11,  5])

In [95]:
y**3

array([  8,   1, 512,   1], dtype=int32)

In [96]:
#get the sin of alll the values
np.sin(y)

array([0.90929743, 0.84147098, 0.98935825, 0.84147098])

In [97]:
#get the cos of alll the values
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [98]:
#get the tan of alll the values
np.tan(y)

array([-2.18503986,  1.55740772, -6.79971146,  1.55740772])

In [103]:
#get the average
v=np.median(np.sum(x)+np.sum(y))
v


22.0

LINEAR ALGRBRA

In [114]:
x=np.full((2,3), 1)
x
y=np.full((3,2), 2)
np.matmul(x,y)

array([[6, 6],
       [6, 6]])

In [116]:
#get the determinant
v=np.identity(3)
np.linalg.det(v)

1.0

Statistics

In [117]:
stats=np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.min(stats)

1

In [119]:
np.max(stats)

6

In [120]:
np.sum(stats)

21

In [121]:
np.sum(stats, axis=0)

array([5, 7, 9])

REORGANISING ARRAYS

In [126]:
X=np.array([[1,2,3,4], [5,6,7,8]])
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [128]:
y=X.reshape((8,1))
y

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [131]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [133]:
#horizontal stack stacking vectors
h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

LOAD DATA FROM FILE

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')

BOOLEAN AND ADVANCED INDEXING

In [ ]:
filedata>50

In [ ]:
filedata[filedata>50]

In [ ]:
np.any(filedata>50, axis=0)

In [ ]:
np.all(filedata>50, axis=0)

In [ ]:
((filedata>50) & (filedata<100))

In [ ]:
(-((filedata>50) & (filedata<100))

In [135]:
x=np.array([5,6,7,8])
x[[1,2,3]]

array([6, 7, 8])

In [ ]:
x[[0,4,5], 3,4,5]